Update install script: sync with current brew/mise setup

diff --git a/run_once_before_install-packages-darwin.sh.tmpl b/run_once_before_install-packages-darwin.sh.tmpl
--- a/run_once_before_install-packages-darwin.sh.tmpl
+++ b/run_once_before_install-packages-darwin.sh.tmpl
@@ -1,119 +1,88 @@
 {{- if eq .chezmoi.os "darwin" -}}
 #!/bin/bash
 
+# System packages (CLI tools managed by mise are excluded)
 FORMULAE=(
-    bat
-    ca-certificates
-    chezmoi
     coreutils
-    eza
-    fzf
-    gettext
-    gh
+    ffmpeg
     git
-    gmp
     gnupg
-    gnutls
-    helm
-    jq
-    k9s
-    kubernetes-cli
-    libassuan
-    libevent
-    libgcrypt
     libgit2
-    libgpg-error
-    libidn2
-    libksba
-    libnghttp2
-    libssh2
-    libtasn1
-    libunistring
-    libusb
     mise
-    ncurses
-    nettle
-    npth
-    oniguruma
-    openssl@3
-    p11-kit
     pcre
-    pcre2
-    pinentry
-    readline
-    ripgrep
-    terraform
-    unbound
-    usage
+    pinentry-mac
+    tmux
+    watch
     zsh
     zsh-autosuggestions
     zsh-fast-syntax-highlighting
 )
 
+# GUI Applications
 CASKS=(
-    aldente
     alt-tab
+    arc
     betterdisplay
     claude
+    deepl
     discord
     excalidrawz
-    figma
     font-cascadia-code-nf
-    font-pretendard
+    github
     google-chrome
-    google-drive
-    httpie
+    iina
     jetbrains-toolbox
     karabiner-elements
     music-decoy
-    naver-whale
-    notion
     obsidian
     orbstack
+    postman
     raycast
     rectangle
     shottr
     slack
-    utm
+    tailscale
     warp
-    wireshark
-    xmind
     zed
-    zoom
 )
 
-# If Homebrew is not installed on the system, it will be installed here
-if test ! $(which brew); then
-   printf '\n\n\e[33mHomebrew not found. \e[0mInstalling Homebrew...'
-   /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
+# Install Homebrew
+if ! command -v brew &> /dev/null; then
+    printf '\n\e[33mHomebrew not found.\e[0m Installing Homebrew...\n'
+    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
 else
-  printf '\n\n\e[0mHomebrew found. Continuing...'
+    printf '\n\e[0mHomebrew found. Continuing...\n'
 fi
 
-# If Oh-my-zsh is not installed on the system, it will be installed here
+# Install Oh-my-zsh
 if [ ! -d ~/.oh-my-zsh ]; then
-  printf '\n\n\e[33mOh-my-zsh not found. \e[0mInstalling Oh-my-zsh...'
-  sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
+    printf '\n\e[33mOh-my-zsh not found.\e[0m Installing Oh-my-zsh...\n'
+    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
 else
-  printf '\n\n\e[0mOh-my-zsh found. Continuing...'
+    printf '\n\e[0mOh-my-zsh found. Continuing...\n'
 fi
 
-# Update homebrew packages
-printf '\nInitiating Homebrew update...\n'
-brew tap homebrew/cask-fonts
-brew tap daipeihust/tap
+# Update Homebrew
+printf '\nUpdating Homebrew...\n'
 brew update
 
-printf '\nInstalling packages...\n'
-brew list --formula ${PACKAGES[@]} || brew install ${PACKAGES[@]}
+# Install formulae
+printf '\nInstalling formulae...\n'
+for formula in "${FORMULAE[@]}"; do
+    brew list --formula "$formula" &>/dev/null || brew install "$formula"
+done
 
-printf '\n\nInstalling cask apps...\n'
-brew list --cask ${CASKS[@]} || brew install --cask ${CASKS[@]}
+# Install casks
+printf '\nInstalling casks...\n'
+for cask in "${CASKS[@]}"; do
+    brew list --cask "$cask" &>/dev/null || brew install --cask "$cask"
+done
 
-printf '\n\nRemoving out of date packages...\n'
+# Cleanup
+printf '\nCleaning up...\n'
 brew cleanup
 
-# kakaotalk
-mas install 869223134
+# After this, run: mise install
+printf '\n\e[32mDone!\e[0m Run "mise install" to install CLI tools.\n'
 
 {{ end -}}
